changelog:
  exclude:
    labels:
      - skip-changelog
      - documentation
      - duplicate
      - good-firs-issue
      - help-wanted
      - wontfix
      - invalid
      - question
    authors:
      - dependabot[bot]
  categories:
    - title: 🚀 Features
      labels:
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🚀 Breaking Changes
      labels:
        - breaking-change
    - title: Other Changes
      labels:
        - "*"
